base_url = "//docs.worldwidetelescope.org/lcapi-guide/1/"
title = "WWT Layer Control API Guide"
description = "Controlling the WWT Windows application with the LCAPI."
theme = "wwtguide"
highlight_code = true

[extra]
github_base = "//github.com/WorldWideTelescope/worldwide-telescope-lcapi-guide"
google_analytics_id = "UA-107473046-3"
